package ui;

import businessLogic.Chess;
import data.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Ellipse2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class ChessBoard extends JPanel implements MouseListener, MouseMotionListener{
    public static boolean movePerformed=false;
    public static int mouseX,mouseY,newMouseX,newMouseY;
    public ChessBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private String piecePath(char piece){
        String path="/resources/";
        char piecesLowerCase[]={'p','k','q','b','n','r'};
        String swapLowerCasePath[]={"whitePawn.png","whiteKing.png","whiteQueen.png"
                ,"whiteBishop.png","whiteKnight.png","whiteRook.png"};
        String swapUpperCasePath[]={"blackPawn.png","blackKing.png","blackQueen.png"
                ,"blackBishop.png","blackKnight.png","blackRook.png"};
        if(Character.isLowerCase(piece)){
            for (int i = 0; i < 6; i++) {
                if(piece==piecesLowerCase[i])path+=swapLowerCasePath[i];
            }
        }else{
            char lowercased=Character.toLowerCase(piece);
            for (int i = 0; i < 6; i++) {
                if(lowercased==piecesLowerCase[i])path+=swapUpperCasePath[i];
            }
        }
//        System.out.println("Path:"+path);
        return path;
    }    
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        int squareSize=56;
        for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
                if((i+j)%2==0){
                    g.setColor(Color.decode("#D5944F"));
                }else{
                    g.setColor(Color.decode("#DDA972"));
                }
                g.fillRect(squareSize*i, squareSize*j, squareSize, squareSize);
            }
            
        }
        
        Board currentBoard=Chess.retriveBoard();
        if(currentBoard!=null){
            Square[][] gameBoard = currentBoard.getGameBoard();
            for(int i=0;i<8;i++){
                for(int j=0;j<8;j++){
                    if(gameBoard[i][j].getPiece()==null)continue;
                    char chr=gameBoard[i][j].getPiece().getPieceSign();
                    String path=piecePath(chr);
                    Image chessPieceImage;
                    chessPieceImage=chessPieceImage=new ImageIcon(getClass().getResource(path)).getImage();
                    g.drawImage(chessPieceImage, j*squareSize, i*squareSize, squareSize, squareSize, this);
                }
            }
        }
    
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if(e.getX()<453 && e.getY()<453){//inside board
            mouseX=e.getX();
            mouseY=e.getY();
            repaint();
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        if(e.getX()<453 && e.getY()<453){//inside board
            newMouseX=e.getX();
            newMouseY=e.getY();
            movePerformed=true;
            if(e.getButton()==MouseEvent.BUTTON1){
                
            }
            repaint();
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
    }
    
    
    
}
